import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WITL-HITL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header/>
          <div class="p-6 max-w-4xl mx-auto">
          {children}
          </div>
        </main>
       
      </body>
    </html>
  );
}
