import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import AppSidebar from "@/components/layout/AppSidebar";
import { Lato } from "next/font/google";
import { Toaster } from "react-hot-toast";
import mongoose from "mongoose";
import { Page } from "@/models/page";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLink } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";

const lato = Lato({ subsets: ["latin"], weight: ['400', '700'] });

export const metadata = {
  title: "WITL-HITL",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children, ...rest }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect('/');
  }

  mongoose.connect(process.env.MONGO_URI);
  const page = await Page.findOne({ owner: session?.user?.email });

  // {console.log("ok "+page)}
  return (
    <html lang="en">
      <body className={lato.className}>
        <Toaster />
        <main className="flex min-h-screen">
          <aside className="bg-white w-48 pt-8 shadow">
            <div className="sticky top-0 pt-2">
            <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto  ">
              <Image
                src={session?.user?.image}
                width={256}
                height={64}
                alt={"avatar"}
              />
            </div>

            {page && (
              <Link 
                target="_blank"
                href={'/'+page.uri}
                className="text-center mt-4 flex gap-2 items-center justify-center"
              >
                <FontAwesomeIcon size="lg" icon={faLink} className="text-blue-500" />
                <span className="text-xl text-gray-500" >/</span>
                <span>{page.uri}</span>
              </Link>
            )}
            <div className="flex justify-center">
              <AppSidebar />
            </div>
            </div>
          </aside>

          <div className="grow">
            {children}
          </div>

        </main>
      </body>
    </html>
  );
}
